version: "3"
services:
  node-app:
    build: .
    ports:
      - 3010:3000
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./.env
    depends_on: 
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    ports: 
      - 6379:6379
volumes:
  mongo-db:
